### ISSUE TITLE
作者您好，我想请问一下执行下载命令的时候出现skipped是什么原因？十分感谢您的工作。

### ISSUE THREAD

**Issue by LinQianhe02grey** [ShuhongChen/vtubers-dataset#1]
![2112](https://github.com/ShuhongChen/vtubers-dataset/assets/165568597/5b6c9d67-870c-4601-84ce-b030ece8cb86)
作者您好，我想请问一下执行下载命令的时候出现skipped是什么原因？十分感谢您的工作。

**Comment by ShuhongChen** [comment]
你好，我估计是这里的问题：
https://github.com/ShuhongChen/vtubers-dataset/blob/a8177f327fd3bedea9c99e99a9a7ed463d33e1f3/_scripts/download_vtubers.py#L152

要是那里吧exception print一下可能跟明确？

**Comment by LinQianhe02grey** [comment]
感谢您的帮助，我改了一下下面代码，成功开始下载图片了
![Uploading 121212211.png…]()
