### ISSUE TITLE
About dataset install step in Ubuntsu24.04

### ISSUE THREAD

**Issue by rkomatsu2020** [ShuhongChen/vtubers-dataset#2]
Hi, thank you providing the interesting dataset :)
I tried to install your dataset following the explanation using my computer with Ubuntsu 24.04. 

However, when I command "make/docker_pull" and "make/shell_docker", the prior one worked and the later one failed with the docker error. (Please see the attached screen shot) 

![image](https://github.com/user-attachments/assets/fedaf9c6-e449-41c5-8370-cffd2ddc0f83)

Please teach me about how to fix it. Thank you.

**Comment by ShuhongChen** [comment]
Hello, it seems it's trying to mount a path that doesn't exist. my guess is
in "machine_config.bashrc" the path to the project directory is wrong, it
should be ".../vtubers-dataset-master" not "... vtubers-dataset-master/_env"

**Comment by rkomatsu2020** [comment]
Thank you for fast replying! It worked and I could download :)

Thanks a lot!!
